// <auto-generated />
using System;
using GasPumpWebService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GasPumpWebService.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20200615091054_initialMigration")]
    partial class initialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("GasPump.PumpFillHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FillDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FillHistories");
                });

            modelBuilder.Entity("GasPump.PumpUsageHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("GasWithdrawAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RemainingGasInPump")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("WithdrawDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UsageHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
